name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sfall_version: 4.2.9
      mpack_version: 4.2.9
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt -qq update >/dev/null 2>&1
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y p7zip wine-stable wine32 >/dev/null 2>&1
          wineboot >/dev/null 2>&1

      - name: Package
        run: ./extra/package.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: npc_armor*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
