name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sfall_version: 4.3.6
      mpack_version: 4.3.6
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          set -xeu -o pipefail
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y p7zip wine-stable wine32
          wineboot

      - name: Package
        run: ./extra/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: npc_armor.zip
          path: npc_armor*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: npc_armor*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
